### PR TITLE
Doxygen file

### PR DESCRIPTION
**Pull request by avcuenes**

### CODE REVIEW

**Comment by avcuenes** [comment]
@ai-winter can you look ? This files generated from your project

**Comment by ai-winter** [comment]
@avcuenes ，we will check later.

**Comment by avcuenes** [comment]
Thanks

**Comment by omigeft** [comment]
Hello, we've come across an error while testing your Dockerfile. Do you know how to fix this issue?


`
passoni@ubuntu:~/ros_motion_planning$ sudo docker build -t ros_motion_planning .
[sudo] password for passoni: 
[+] Building 27.9s (7/13)                                                                                                               
 => [internal] load build definition from Dockerfile                                                                               0.0s
 => => transferring dockerfile: 1.07kB                                                                                             0.0s
 => [internal] load .dockerignore                                                                                                  0.0s
 => => transferring context: 2B                                                                                                    0.0s
 => [internal] load metadata for docker.io/osrf/ros:noetic-desktop-full                                                            0.0s
 => [1/9] FROM docker.io/osrf/ros:noetic-desktop-full                                                                              0.0s
 => [internal] load build context                                                                                                  0.5s
 => => transferring context: 462.40kB                                                                                              0.4s
 => CACHED [2/9] WORKDIR /ws                                                                                                       0.0s
 => ERROR [3/9] RUN apt-get update     && apt-get -y --quiet --no-install-recommends install     gcc     git     libxml2-dev      27.8s
------                                                                                                                                  
 > [3/9] RUN apt-get update     && apt-get -y --quiet --no-install-recommends install     gcc     git     libxml2-dev     libxslt-dev     python3     python3-pip    python-is-python3    ros-noetic-amcl     ros-noetic-base-local-planner     ros-noetic-map-server     ros-noetic-move-base     ros-noetic-navfn:                                                                                                    
#0 1.334 Get:1 http://archive.ubuntu.com/ubuntu focal InRelease [265 kB]                                                                
#0 1.467 Get:2 http://security.ubuntu.com/ubuntu focal-security InRelease [114 kB]                                                      
#0 3.025 Get:3 http://archive.ubuntu.com/ubuntu focal-updates InRelease [114 kB]
#0 3.389 Get:4 http://security.ubuntu.com/ubuntu focal-security/main amd64 Packages [3290 kB]
#0 3.725 Get:5 http://archive.ubuntu.com/ubuntu focal-backports InRelease [108 kB]
#0 4.426 Get:6 http://archive.ubuntu.com/ubuntu focal/restricted amd64 Packages [33.4 kB]
#0 4.859 Get:7 http://archive.ubuntu.com/ubuntu focal/main amd64 Packages [1275 kB]
#0 6.828 Get:8 http://security.ubuntu.com/ubuntu focal-security/restricted amd64 Packages [3142 kB]
#0 7.865 Get:9 http://security.ubuntu.com/ubuntu focal-security/universe amd64 Packages [1156 kB]
#0 8.180 Get:10 http://archive.ubuntu.com/ubuntu focal/multiverse amd64 Packages [177 kB]
#0 8.232 Get:11 http://security.ubuntu.com/ubuntu focal-security/multiverse amd64 Packages [29.7 kB]
#0 8.526 Get:12 http://archive.ubuntu.com/ubuntu focal/universe amd64 Packages [11.3 MB]
#0 21.06 Get:13 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 Packages [3770 kB]
#0 21.85 Err:14 http://packages.ros.org/ros/ubuntu focal InRelease
#0 21.85   Could not connect to packages.ros.org:80 (101.198.192.92). - connect (111: Connection refused)
#0 22.95 Get:15 http://archive.ubuntu.com/ubuntu focal-updates/restricted amd64 Packages [3292 kB]
#0 24.81 Get:16 http://archive.ubuntu.com/ubuntu focal-updates/universe amd64 Packages [1450 kB]
#0 25.24 Get:17 http://archive.ubuntu.com/ubuntu focal-updates/multiverse amd64 Packages [32.4 kB]
#0 25.24 Get:18 http://archive.ubuntu.com/ubuntu focal-backports/main amd64 Packages [55.2 kB]
#0 25.29 Get:19 http://archive.ubuntu.com/ubuntu focal-backports/universe amd64 Packages [28.6 kB]
#0 25.34 Fetched 29.7 MB in 25s (1209 kB/s)
#0 25.34 Reading package lists...
#0 26.37 W: Failed to fetch http://packages.ros.org/ros/ubuntu/dists/focal/InRelease  Could not connect to packages.ros.org:80 (101.198.192.92). - connect (111: Connection refused)
#0 26.37 W: Some index files failed to download. They have been ignored, or old ones used instead.
#0 26.41 Reading package lists...
#0 27.41 Building dependency tree...
#0 27.63 Reading state information...
#0 27.67 E: Unable to locate package ros-noetic-amcl
#0 27.67 E: Unable to locate package ros-noetic-base-local-planner
#0 27.67 E: Unable to locate package ros-noetic-map-server
#0 27.67 E: Unable to locate package ros-noetic-move-base
#0 27.67 E: Unable to locate package ros-noetic-navfn
------
Dockerfile:10
--------------------
   9 |     # Install additional dependencies
  10 | >>> RUN apt-get update \
  11 | >>>     && apt-get -y --quiet --no-install-recommends install \
  12 | >>>     gcc \
  13 | >>>     git \
  14 | >>>     libxml2-dev \
  15 | >>>     libxslt-dev \
  16 | >>>     python3 \
  17 | >>>     python3-pip\ 
  18 | >>>     python-is-python3\
  19 | >>>     ros-noetic-amcl \
  20 | >>>     ros-noetic-base-local-planner \
  21 | >>>     ros-noetic-map-server \
  22 | >>>     ros-noetic-move-base \
  23 | >>>     ros-noetic-navfn
  24 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c apt-get update     && apt-get -y --quiet --no-install-recommends install     gcc     git     libxml2-dev     libxslt-dev     python3     python3-pip    python-is-python3    ros-noetic-amcl     ros-noetic-base-local-planner     ros-noetic-map-server     ros-noetic-move-base     ros-noetic-navfn" did not complete successfully: exit code: 100
`

**Comment by avcuenes** [comment]
I try your command there is no problem on my desktop.I think your connection is failed can you try again?
and can you write your terminal the following command 

```bash
sudo apt install ros-noetic-amcl
```

**Pull request merged**
